# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code2do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
