# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code2do', '0004_auto_20160917_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='handle',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
