# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code2do', '0005_auto_20160917_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='code2do.Users'),
            preserve_default=False,
        ),
    ]
