# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code2do', '0006_problems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code2do.Users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
